name: Build and Deploy
run-name: Build and deploy docker images to ECR

on: [push, workflow_dispatch]
jobs:
    build_doom_job:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v4.3.1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-west-2
              # role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
              # role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
              # role-duration-seconds: 1200
              # role-session-name: MySessionName

          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2

          - name: Build, tag, and push docker image to Amazon ECR
            env:
              REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              REPOSITORY: tommydeleteme
              IMAGE_TAG: ${{ github.sha }}
            working-directory: ./Docker
            run: |
              docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
              docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
